name: PyPI

on:
  push:

jobs:
  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python dependencies
        run: uv sync

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          sed -i "s|version=\"0.0.0\",|version=\"${GITHUB_REF/refs\/tags\//}\",|g" setup.py
          sed -i "s|version = \"0.0.0\"|version = \"${GITHUB_REF/refs\/tags\//}\"|g" pyproject.toml
          uv run python setup.py sdist bdist_wheel
          uv run twine upload dist/*
